:output:
  User:
    :options:
      :fields:
        - id
        - full_name
        - email
        - mobile
  Game:
    :options:
      :fields:
        - id
        - name
        - user_id
        - status
        - parameters
        - permalink
        - preregistered?

  GameProfile:
    :options:
      :fields:
        - id
        - full_name
        - mobile
        - user_id
        - game_id
        - kills
        - details
        - is_alive?
        - died_at
        - hunter_id